### PR TITLE
FDPON-20079 inactive executors filtering logic in ExecutorGroup

### PR DESCRIPTION
**Pull request by thrinath500**

### CODE REVIEW

**Review by aryaKetan — APPROVED** [review]

**Review by aryaKetan — APPROVED** [review]
Approved

**Review by aryaKetan — APPROVED** [review]
LGTM

**Review by aryaKetan — APPROVED** [review]

**Review by mittalnanu — APPROVED** [review]
What is meant by inactive executors? I am approving as arya has approved it

**Review by mittalnanu — APPROVED** [review]
LGTM

**Pull request merged**
